import type { MarkerId } from "./marker-id";
import type {
  MeasurementGroup,
  MeasurementId,
  MeasurementUnit,
} from "./measurement-id";

export type MeasurementDef = {
  id: MeasurementId;
  label: string;
  description: string;
  unit: MeasurementUnit;
  group: MeasurementGroup;
  markers: readonly MarkerId[];
};

export const MEASUREMENT_DEFS: readonly MeasurementDef[] = [
  {
    id: "leftEarLength",
    label: "Left ear length",
    description: "Helix top to the left tragus / earlobe landmark.",
    unit: "mm",
    group: "left-profile",
    markers: ["leftEarTop", "leftEarBottom"],
  },
  {
    id: "leftForeheadAngle",
    label: "Left side forehead angle",
    description: "Angle at the left temple: hairline → temple → outer brow.",
    unit: "deg",
    group: "left-profile",
    markers: ["hairlineCenter", "leftTemple", "leftBrowOuter"],
  },
  {
    id: "leftJawAngle",
    label: "Left side jaw angle",
    description: "Gonial angle: left ear → jaw corner → chin.",
    unit: "deg",
    group: "left-profile",
    markers: ["leftEarBottom", "leftGonion", "chin"],
  },
  {
    id: "leftEarToEye",
    label: "Distance from the left ear to the left eye",
    description: "Left tragus to the left outer canthus.",
    unit: "mm",
    group: "left-profile",
    markers: ["leftEarBottom", "leftEyeOuter"],
  },
  {
    id: "leftNostrilToEar",
    label: "Left side of the left nostril till the left ear",
    description: "Left alar rim to the left tragus.",
    unit: "mm",
    group: "left-profile",
    markers: ["leftNostril", "leftEarBottom"],
  },
  {
    id: "leftEyeHeight",
    label: "Left eye height",
    description: "Upper to lower eyelid at the left palpebral fissure.",
    unit: "mm",
    group: "left-eye",
    markers: ["leftEyeTop", "leftEyeBottom"],
  },
  {
    id: "leftEyeWidth",
    label: "Left eye width",
    description: "Left inner to outer canthus.",
    unit: "mm",
    group: "left-eye",
    markers: ["leftEyeInner", "leftEyeOuter"],
  },
  {
    id: "leftEyeToEyebrow",
    label: "Distance from left eye to left eyebrow",
    description: "Left upper lid to the left brow arch.",
    unit: "mm",
    group: "left-eye",
    markers: ["leftEyeTop", "leftBrowTop"],
  },
  {
    id: "leftEyebrowWidth",
    label: "Left eyebrow width",
    description: "Thickness of the left brow at the arch.",
    unit: "mm",
    group: "left-eye",
    markers: ["leftBrowTop", "leftBrowBottom"],
  },
  {
    id: "leftEyebrowLength",
    label: "Left eyebrow length",
    description: "Left brow inner to outer tail.",
    unit: "mm",
    group: "left-eye",
    markers: ["leftBrowInner", "leftBrowOuter"],
  },
  {
    id: "leftEyebrowToHairline",
    label: "Distance from left eyebrow to hairline",
    description: "Left brow arch to the left hairline.",
    unit: "mm",
    group: "left-eye",
    markers: ["leftBrowTop", "hairlineLeft"],
  },
  {
    id: "distanceBetweenEyebrows",
    label: "Distance between eyebrows",
    description: "Medial ends of the left and right brows.",
    unit: "mm",
    group: "center",
    markers: ["leftBrowInner", "rightBrowInner"],
  },
  {
    id: "distanceBetweenEyes",
    label: "Distance between eyes",
    description: "Interpupillary distance, iris center to iris center.",
    unit: "mm",
    group: "center",
    markers: ["leftIrisCenter", "rightIrisCenter"],
  },
  {
    id: "browMidpointToHairline",
    label: "Middle of the eyebrows to the hairline",
    description: "Midpoint between the brows up to the central hairline.",
    unit: "mm",
    group: "center",
    markers: ["leftBrowInner", "rightBrowInner", "hairlineCenter"],
  },
  {
    id: "foreheadCurvature",
    label: "Curvature of the forehead",
    description:
      "How far the hairline bows from a straight left-to-right temple line.",
    unit: "mm",
    group: "center",
    markers: ["foreheadLeft", "hairlineCenter", "foreheadRight"],
  },
  {
    id: "noseLength",
    label: "Length of the nose",
    description: "Nasion (between the eyes) to the subnasale.",
    unit: "mm",
    group: "center",
    markers: ["nasion", "subnasale"],
  },
  {
    id: "noseToLip",
    label: "Distance from nose to lip",
    description: "Subnasale to the upper vermilion border.",
    unit: "mm",
    group: "center",
    markers: ["subnasale", "upperLip"],
  },
  {
    id: "lipLength",
    label: "Lip length",
    description: "Vertical height of the lips, upper to lower vermilion.",
    unit: "mm",
    group: "center",
    markers: ["upperLip", "lowerLip"],
  },
  {
    id: "lipWidth",
    label: "Lip width",
    description: "Left to right mouth corner (cheilion to cheilion).",
    unit: "mm",
    group: "center",
    markers: ["leftMouthCorner", "rightMouthCorner"],
  },
  {
    id: "lipToChin",
    label: "Distance from lip to chin",
    description: "Lower vermilion to the chin tip (menton).",
    unit: "mm",
    group: "center",
    markers: ["lowerLip", "chin"],
  },
  {
    id: "chinWidth",
    label: "Chin width",
    description: "Left to right chin body.",
    unit: "mm",
    group: "center",
    markers: ["chinLeft", "chinRight"],
  },
  {
    id: "rightEyebrowToHairline",
    label: "Distance from right eyebrow to hairline",
    description: "Right brow arch to the right hairline.",
    unit: "mm",
    group: "right-eye",
    markers: ["rightBrowTop", "hairlineRight"],
  },
  {
    id: "rightEyebrowLength",
    label: "Right eyebrow length",
    description: "Right brow inner to outer tail.",
    unit: "mm",
    group: "right-eye",
    markers: ["rightBrowInner", "rightBrowOuter"],
  },
  {
    id: "rightEyebrowWidth",
    label: "Right eyebrow width",
    description: "Thickness of the right brow at the arch.",
    unit: "mm",
    group: "right-eye",
    markers: ["rightBrowTop", "rightBrowBottom"],
  },
  {
    id: "rightEyeToEyebrow",
    label: "Distance from right eye to right eyebrow",
    description: "Right upper lid to the right brow arch.",
    unit: "mm",
    group: "right-eye",
    markers: ["rightEyeTop", "rightBrowTop"],
  },
  {
    id: "rightEyeWidth",
    label: "Right eye width",
    description: "Right inner to outer canthus.",
    unit: "mm",
    group: "right-eye",
    markers: ["rightEyeInner", "rightEyeOuter"],
  },
  {
    id: "rightEyeHeight",
    label: "Right eye height",
    description: "Upper to lower eyelid at the right palpebral fissure.",
    unit: "mm",
    group: "right-eye",
    markers: ["rightEyeTop", "rightEyeBottom"],
  },
  {
    id: "rightNostrilToEar",
    label: "Right side of the right nostril till the right ear",
    description: "Right alar rim to the right tragus.",
    unit: "mm",
    group: "right-profile",
    markers: ["rightNostril", "rightEarBottom"],
  },
  {
    id: "rightEarToEye",
    label: "Distance from the right ear to the right eye",
    description: "Right tragus to the right outer canthus.",
    unit: "mm",
    group: "right-profile",
    markers: ["rightEarBottom", "rightEyeOuter"],
  },
  {
    id: "rightJawAngle",
    label: "Right side jaw angle",
    description: "Gonial angle: right ear → jaw corner → chin.",
    unit: "deg",
    group: "right-profile",
    markers: ["rightEarBottom", "rightGonion", "chin"],
  },
  {
    id: "rightForeheadAngle",
    label: "Right side forehead angle",
    description: "Angle at the right temple: hairline → temple → outer brow.",
    unit: "deg",
    group: "right-profile",
    markers: ["hairlineCenter", "rightTemple", "rightBrowOuter"],
  },
  {
    id: "rightEarLength",
    label: "Right ear length",
    description: "Helix top to the right tragus / earlobe landmark.",
    unit: "mm",
    group: "right-profile",
    markers: ["rightEarTop", "rightEarBottom"],
  },
];
