import type { MarkerId } from "./marker-id";

/** Key anthropometric points drawn as numbered markers (iris scale points stay hidden). */
export const VISIBLE_MARKER_IDS: readonly MarkerId[] = [
  "leftEarTop",
  "leftEarBottom",
  "leftTemple",
  "leftGonion",
  "leftEyeOuter",
  "leftEyeInner",
  "leftEyeTop",
  "leftEyeBottom",
  "leftBrowOuter",
  "leftBrowInner",
  "leftBrowTop",
  "leftNostril",
  "hairlineLeft",
  "hairlineCenter",
  "hairlineRight",
  "nasion",
  "noseTip",
  "subnasale",
  "leftMouthCorner",
  "rightMouthCorner",
  "upperLip",
  "lowerLip",
  "chin",
  "chinLeft",
  "chinRight",
  "rightBrowInner",
  "rightBrowTop",
  "rightBrowOuter",
  "rightEyeInner",
  "rightEyeOuter",
  "rightEyeTop",
  "rightEyeBottom",
  "rightNostril",
  "rightTemple",
  "rightGonion",
  "rightEarTop",
  "rightEarBottom",
];
